.github/workflows/apply-command.yml, .github/workflows/chatops.yml, .github/workflows/help-command.yml, .github/workflows/idempotence-command.yml, .github/workflows/plan-command.yml, .github/workflows/sca-command.yml, .github/workflows/validate-command.yml
Add repository name as input for chatops workflows.
Allow to run the workflows on PRs created from a fork.
Change is based on https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/pull/376
=> ci: Add repository input for chatops workflows

modules/bootstrap/README.md, modules/bootstrap/versions.tf
This PR adds a new AzureRM provider version constraint that limit maximum provider version to `3.95` in the `bootstrap` module (temporary solution). 
Our examples utilising `bootstrap` module currently don't work with the newest AzureRM provider version (this is observed since version `3.96`). On HashiCorp side, it seems that they addressed this [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/25353) but the fix hasn't been released yet.
Once the problem is fixed on the HashiCorp side, we will switch to the newest AzureRM provider version.
=> fix: Restrict maximum AzureRM provider version for bootstrap module

.pre-commit-config.yaml, .terraform-docs-internal.yml, modules/test_infrastructure/.README.md
We introduced `test_infrastructure` module as internal submodule from TF Registry perspective. This means that module's README file should have a leading dot in its name (`.README.md`). We needed to automate the generation of README files for internal submodules.
This PR introduces separate **terraform-docs configuration file** for internal submodules and additional **terraform-docs hook in pre-commit configuration file** for `test_infrastructure` module.
#30 
Tested locally with `pre-commit` command.
The terraform-docs hook is ran twice now, like that:
=> refactor: Fix README generation for internal submodules

modules/virtual_network_gateway/README.md, modules/virtual_network_gateway/variables.tf
This PR adds a **tr** closing tag to the table in one of the VNG module's variable description.
`pan.dev` CI failed to generate the docs due to lack of `</tr>` in a table in VNG module's README file.
Locally
=> docs: Add tr closing tag to the table in VNG module

modules/loadbalancer/main.tf
There was a typo in a `public_ip_resource_group_name` variable name within data source block in `main.tf` of the `loadbalancer` module.
It was impossible to source a Public IP resource for the Load Balancer from another Resource Group.
Locally from my workstation.
=> fix: Fix sourcing an LB PIP from another RG

examples/common_vmseries/README.md, examples/common_vmseries/main.tf, examples/common_vmseries/variables.tf, examples/common_vmseries_and_autoscale/README.md, examples/common_vmseries_and_autoscale/main.tf, examples/common_vmseries_and_autoscale/variables.tf, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries/main.tf, examples/dedicated_vmseries/variables.tf, examples/dedicated_vmseries_and_autoscale/README.md, examples/dedicated_vmseries_and_autoscale/main.tf, examples/dedicated_vmseries_and_autoscale/variables.tf, examples/gwlb_with_vmseries/README.md, examples/gwlb_with_vmseries/main.tf, examples/gwlb_with_vmseries/variables.tf, modules/test_infrastructure/.README.md, modules/test_infrastructure/main.tf, modules/test_infrastructure/variables.tf
This code contains enhancement to the test_infrastructure_module. Adds support for the VNet peering to enable Remote Gateway use. Also minor change to add tags to the test VMs. Includes also small fix in examples that moves "disable_bgp_route_propagation" parameter under route tables instead of NSGs. 
The current version does not support VNet peering with Remote Gateway in the hub. Disable route propagation is the parameter supported by Route Table instead of Network Security Group. 
Deployed in the lab environment to confirm VNet peering with use of Remote Gateway and disabled route propagation. 
=> feat: Add VNet peering parameters support to test_infrastructure module

modules/loadbalancer/main.tf
This PR adds a lifecycle block with `create_before_destroy` option set to `true` for a `azurerm_public_ip` resource in `loadbalancer` module.
The Azure API didn't allow to replace the public ip resource in Public Load Balancer Frontend when changed in tfvars.
#74 
By deploying one of the examples and replicating the problem.
=> fix: Allow to change Public IP for an LB Frontend

modules/loadbalancer/main.tf
This PR adds a lifecycle block with `create_before_destroy` option set to `true` for a `azurerm_lb_probe` resource in `loadbalancer` module.
The Azure API didn't allow to replace the health probe resource in Load Balancer Rule when changed in tfvars.
#75 
By deploying one of the examples and replicating the problem.
=> fix: Allow to change Health Probe for an LB Rule

examples/common_vmseries/README.md, examples/common_vmseries/main.tf, examples/common_vmseries/variables.tf, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries/main.tf, examples/dedicated_vmseries/variables.tf, examples/gwlb_with_vmseries/README.md, examples/gwlb_with_vmseries/main.tf, examples/gwlb_with_vmseries/variables.tf, examples/standalone_vmseries/README.md, examples/standalone_vmseries/main.tf, examples/standalone_vmseries/variables.tf, modules/vmseries/README.md, modules/vmseries/main.tf, modules/vmseries/variables.tf
- Add possibility to attach vmseries interfaces to existing AppGW .
- This PR closes #88 .
- No current way to attach existing VMSeries interfaces to AppGW just like you would attach it to a regular Loadbalancer (from within the module).
=> feat(vmseries): VMSeries appgw backend pool association

examples/dedicated_vmseries/README.md, modules/appgw/.header.md, modules/appgw/README.md, modules/gwlb/.header.md, modules/gwlb/README.md, modules/loadbalancer/.header.md, modules/loadbalancer/README.md, modules/natgw/.header.md, modules/natgw/README.md, modules/virtual_machine/.README.md, modules/virtual_network_gateway/.header.md, modules/virtual_network_gateway/README.md, modules/vmss/.header.md, modules/vmss/README.md, modules/vmss/versions.tf, modules/vnet/.header.md, modules/vnet/README.md
The changes apply to the snippets in the README because they did not reflect the modules code after the refactor.
#81 
The snippets were tested manually. After the applied changes, all snippets no longer throw errors during terraform plan.
=> docs: Documentation bug fixes in README snippets

modules/bootstrap/main.tf
This PR disables the use of local users for Azure Storage Account (enabled by default) within the `bootstrap` module.
In `checkov` version `3.2.255`, the hook failed due to check `CKV_AZURE_244` ("Avoid the use of local users for Azure Storage unless necessary").
Manually deployed an example with full bootstrap to make sure it's still working as intended.
=> fix: Disable the use of local users for Storage Account

.pre-commit-config.yaml
This PR reverts Terraform Docs version to latest working properly (`v1.94.2`)
Terraform Docs was not working properly on version `1.96.1` (new READMEs were not generated despite changes in the code)
On local workstation
=> fix: Revert terraform_docs version to v1.94.2

examples/dedicated_vmseries/main_test.go, examples/gwlb_with_vmseries/main_test.go
This PR removes creating a `bootstrap_storages` option in the Terratest GO files within the examples in order to fix the testing pipelines.
We no longer use full bootstrap as a default bootstrap option in any of the examples.
Release CI is failing because of that.
=> fix: Remove bootstrap_storages option from the testing pipeline

examples/common_vmseries/README.md, examples/common_vmseries/variables.tf, examples/common_vmseries_and_autoscale/README.md, examples/common_vmseries_and_autoscale/variables.tf, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries/variables.tf, examples/dedicated_vmseries_and_autoscale/README.md, examples/dedicated_vmseries_and_autoscale/variables.tf, examples/gwlb_with_vmseries/README.md, examples/gwlb_with_vmseries/variables.tf, examples/standalone_vmseries/README.md, examples/standalone_vmseries/variables.tf
This PR adds a default value of `["1", "2", "3"]` to `zones` property in `load_balancers` map across all examples.
Default value was not inherited from the `loadbalancer` module and non-zonal LB frontends were created, instead of zone-redundant LB frontends as intended.
Deployed one of the examples manually.
=> fix: Make LB Frontends zone-redundant in examples

modules/virtual_network_gateway/README.md, modules/virtual_network_gateway/main.tf, modules/virtual_network_gateway/variables.tf, tests/virtual_network_gateway/main.tf
This PR:
* Fixes integration with `public_ip` module (allowing to source pip outside VNG module)
* Fixes creating the VNG without Custom APIPA BGP peering addresses
* Fixes the conditional check preventing from creating Generation2 VNGs
Things mentioned above didn't work properly.
Manually deploying the module.
=> fix(virtual_network_gateway): Fix several issues with VNG module

modules/bootstrap/README.md, modules/bootstrap/main.tf, modules/bootstrap/versions.tf
This PR replaces deprecated `storage_account_name` property with `storage_account_id` property within the `azurerm_storage_share` resource.
New property was introduced in `azurerm` provider version **4.9** so the module's version constraints got bumped.
Property got deprecated.
Deploying locally.
=> fix(bootstrap): Replace deprecated storage_account_name property

modules/route_server/.header.md, modules/route_server/README.md, modules/route_server/main.tf, modules/route_server/main_test.go, modules/route_server/outputs.tf, modules/route_server/variables.tf, modules/route_server/versions.tf
This PR introduces a new `route_server` module.
Need for deploying Route Server resources to establish a BGP peering with VM-Series firewall or vION SD-WAN appliance and propagate learnt routes into a VNET.
Deploying the module manually.
=> feat(route_server): Introduce Route Server module

examples/common_vmseries/README.md, examples/common_vmseries/variables.tf, examples/common_vmseries_and_autoscale/README.md, examples/common_vmseries_and_autoscale/variables.tf, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries/variables.tf, examples/dedicated_vmseries_and_autoscale/README.md, examples/dedicated_vmseries_and_autoscale/variables.tf, examples/gwlb_with_vmseries/README.md, examples/gwlb_with_vmseries/variables.tf, examples/standalone_vmseries/README.md, examples/standalone_vmseries/variables.tf
This PR adds 2 missing vnet properties (`vnet_encryption` & `ddos_protection_plan_id`) to `test_infrastructure` variable in all examples.
It's already available in the module but was not populated into the examples.
Locally by deploying one of the examples.
=> feat: Add new vnet properties to test_infrastructure variable in examples

modules/virtual_network_gateway/main.tf
This PR adds error handling to `azurerm_public_ip` resource `for_each` conditions.
Module was failing to create a Virtual Network Gateway in Active/Passive mode because the `for_each` conditions for secondary public IP resource failed.
Locally.
=> fix(virtual_network_gateway): Active/Passive VNG creation fix

examples/common_vmseries_and_autoscale/.header.md, examples/common_vmseries_and_autoscale/README.md, examples/dedicated_vmseries/.header.md, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries_and_autoscale/.header.md, examples/dedicated_vmseries_and_autoscale/README.md, examples/gwlb_with_vmseries/.header.md, examples/gwlb_with_vmseries/README.md, examples/standalone_vmseries/.header.md, examples/standalone_vmseries/README.md
This PR updates terraform output names in examples READMEs:
`username` -> `usernames`
`password` -> `passwords`
Some terraform output commands listed in the README didn't work.
=> docs: Correct terraform output names in examples READMEs

modules/bootstrap/main.tf
This PR updates the `storage_share_id` property within resources in `bootstrap` module to use file share's URL instead of an ID.
#130 
Deployed one of the examples with full bootstrap manually.
=> fix(bootstrap): Replace file shares IDs with URLs for storage_share_id property

examples/common_vmseries/README.md, examples/common_vmseries/main.tf, examples/common_vmseries/variables.tf, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries/main.tf, examples/dedicated_vmseries/variables.tf, examples/gwlb_with_vmseries/README.md, examples/gwlb_with_vmseries/main.tf, examples/gwlb_with_vmseries/variables.tf, examples/standalone_vmseries/README.md, examples/standalone_vmseries/main.tf, examples/standalone_vmseries/variables.tf, modules/vmseries/README.md, modules/vmseries/main.tf, modules/vmseries/variables.tf
This PR introduces the ability to modify the IP configuration name in the Azure VM network interface, providing greater flexibility in network configuration.
Currently, the IP configuration name in the Azure VM network interface is hardcoded, limiting flexibility in network setups. 
Deployed manually.
=> feat(vmseries): Allow customization of IP configuration name in Azure VM interface

.github/workflows/chatops.yml, .github/workflows/help-command.yml, .github/workflows/hub_sync.yml, .github/workflows/sca-command.yml
GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> ci: Pin GitHub Actions

.github/actions/sub_cleanup/action.yml, .github/actions/terratest/action.yml, .github/workflows/chatops.yml, .github/workflows/sca-command.yml
This PR finishes the job of PR #139 and pins GitHub Actions versions to full length commit SHA.
GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> ci: Pin remaining GitHub Actions

examples/common_vmseries/.header.md, examples/common_vmseries/README.md, examples/common_vmseries_and_autoscale/.header.md, examples/common_vmseries_and_autoscale/README.md, examples/dedicated_vmseries/.header.md, examples/dedicated_vmseries/README.md, examples/dedicated_vmseries_and_autoscale/.header.md, examples/dedicated_vmseries_and_autoscale/README.md, examples/gwlb_with_vmseries/.header.md, examples/gwlb_with_vmseries/README.md, examples/standalone_vmseries/.header.md, examples/standalone_vmseries/README.md
This PR adds `swfw` property to heredoc of each example README (except for `standalone_panorama` ???). The value can be either `cloudngfw` or `vmseries`.
#28
=> docs: Add swfw property to examples heredoc

examples/panorama_standalone/example.tfvars, examples/vmseries_gwlb/example.tfvars, examples/vmseries_standalone/example.tfvars, examples/vmseries_transit_vnet_common/example.tfvars, examples/vmseries_transit_vnet_common_autoscale/example.tfvars, examples/vmseries_transit_vnet_dedicated/example.tfvars, examples/vmseries_transit_vnet_dedicated_autoscale/example.tfvars
PAN-OS version got bumped for both VM-Series and Panorama to `11.1.6-h7` in all examples.
Taking advantage of new PAN-OS features and better compatibility with SCM.
Ran locally.
=> feat: Bump PAN-OS version to 11.1.6-h7

examples/vmseries_gwlb/README.md, examples/vmseries_gwlb/main.tf, examples/vmseries_gwlb/variables.tf, examples/vmseries_standalone/README.md, examples/vmseries_standalone/main.tf, examples/vmseries_standalone/variables.tf, examples/vmseries_transit_vnet_common/README.md, examples/vmseries_transit_vnet_common/main.tf, examples/vmseries_transit_vnet_common/variables.tf, examples/vmseries_transit_vnet_common_autoscale/README.md, examples/vmseries_transit_vnet_common_autoscale/main.tf, examples/vmseries_transit_vnet_common_autoscale/variables.tf, examples/vmseries_transit_vnet_dedicated/README.md, examples/vmseries_transit_vnet_dedicated/main.tf, examples/vmseries_transit_vnet_dedicated/variables.tf, examples/vmseries_transit_vnet_dedicated_autoscale/README.md, examples/vmseries_transit_vnet_dedicated_autoscale/main.tf, examples/vmseries_transit_vnet_dedicated_autoscale/variables.tf, modules/vmseries/README.md, modules/vmseries/main.tf, modules/vmseries/variables.tf, modules/vmss/README.md, modules/vmss/main.tf, modules/vmss/variables.tf
Add support for AI Runtime Security image with a single switch (boolean value) passed to either `vmseries` or `vmss` modules. The flag is called `use_airs` and is `false` by default.
#160 
Ran locally.
=> feat: Add easy AIRS support to vmseries and vmss modules

examples/vmseries_gwlb/templates/bootstrap-gwlb.tftpl, examples/vmseries_transit_vnet_common/templates/bootstrap_common.tmpl, examples/vmseries_transit_vnet_common/templates/bootstrap_inbound.tmpl, examples/vmseries_transit_vnet_common/templates/bootstrap_obew.tmpl, examples/vmseries_transit_vnet_common_autoscale/templates/bootstrap_common.tmpl, examples/vmseries_transit_vnet_common_autoscale/templates/bootstrap_inbound.tmpl, examples/vmseries_transit_vnet_common_autoscale/templates/bootstrap_obew.tmpl, examples/vmseries_transit_vnet_dedicated/templates/bootstrap_common.tmpl, examples/vmseries_transit_vnet_dedicated/templates/bootstrap_inbound.tmpl, examples/vmseries_transit_vnet_dedicated/templates/bootstrap_obew.tmpl, examples/vmseries_transit_vnet_dedicated_autoscale/templates/bootstrap_common.tmpl, examples/vmseries_transit_vnet_dedicated_autoscale/templates/bootstrap_inbound.tmpl, examples/vmseries_transit_vnet_dedicated_autoscale/templates/bootstrap_obew.tmpl
This PR adds `<advance-routing>yes</advance-routing>` tag to XML bootstrap templates.
Knowledge Article 000028560 (for some PAN-OS versions, this tag is required in addition to bootstrap parameter in init-cfg for Advanced Routing Engine to function properly).
Deployed locally.
=> fix: Add ARE tag to XML bootstrap templates

examples/cloudngfw_centralized_single_vwan/README.md, examples/cloudngfw_centralized_single_vwan/variables.tf, examples/cloudngfw_centralized_vnet/README.md, examples/cloudngfw_centralized_vnet/variables.tf, examples/cloudngfw_distributed/README.md, examples/cloudngfw_distributed/variables.tf, examples/panorama_standalone/README.md, examples/panorama_standalone/variables.tf, examples/vmseries_gwlb/README.md, examples/vmseries_gwlb/variables.tf, examples/vmseries_standalone/README.md, examples/vmseries_standalone/variables.tf, examples/vmseries_transit_vnet_common/README.md, examples/vmseries_transit_vnet_common/variables.tf, examples/vmseries_transit_vnet_common_autoscale/README.md, examples/vmseries_transit_vnet_common_autoscale/variables.tf, examples/vmseries_transit_vnet_dedicated/README.md, examples/vmseries_transit_vnet_dedicated/variables.tf, examples/vmseries_transit_vnet_dedicated_autoscale/README.md, examples/vmseries_transit_vnet_dedicated_autoscale/variables.tf, modules/public_ip/README.md, modules/public_ip/main.tf, modules/public_ip/variables.tf, modules/vmss/README.md, modules/vmss/main.tf, modules/vmss/variables.tf
This PR adds support for sourcing a Public IP Prefix resource by specifying its ID instead of name and resource group name, when creating a new Public IP resource using `public_ip` or `vmss` module.
#157 
Ran locally.
=> feat: Add PIP Prefix ID as an option to source a PIP Prefix
